### PR TITLE
Add support for AMD Rome

### PR DESCRIPTION
**Pull request by krenzland**
Add support for rome architecture.
SeisSol commit follows afterwards with specific compiler settings.

@uphoffc It's a bit messy to switch to hsw during code generation but the entire thing is very messy... Do you have a better idea?

Definitely squash before merging. First commit was very wrong.

### CODE REVIEW

**Comment by uphoffc** [comment]
Mabye one could work with host_arch, device_arch or however Ravil called them?

Why do you need the alias at all if it does the same as hsw?

**Comment by krenzland** [comment]
Different compiler settings. Maybe later different codegen as well. It's not the same architecture, hsw has just similar simd.

**Review by uphoffc — APPROVED** [review]
For now its ok. Should be addressed in the refactoring of gemmgen.py.

you might also add blis to rome?

**Comment by krenzland** [comment]
Yes, added. Thanks!

**Pull request merged**
